package com.github.mdr.mash.evaluator

import com.github.mdr.mash.functions.MashFunction
import com.github.mdr.mash.functions.Parameter
import com.github.mdr.mash.functions.ParameterModel
import com.github.mdr.mash.ns.os.RunFunction
import com.github.mdr.mash.subprocesses.ProcessRunner
import com.github.mdr.mash.runtime.MashString
import com.github.mdr.mash.runtime.MashList
import com.github.mdr.mash.runtime.MashUnit

/**
 * A function generated by the "!nano" syntax
 */
case class SystemCommandFunction(command: String) extends MashFunction(nameOpt = None) {

  object Params {
    val Args = Parameter("args", "Arguments", isVariadic = true)
  }
  import Params._

  val params = ParameterModel(Seq(Args))

  def apply(arguments: Arguments): MashUnit = {
    val boundParams = params.validate(arguments)
    val args = boundParams(Args) match {
      case MashList(xs: MashList) ⇒ xs.items
      case xs: MashList           ⇒ xs.items
      case x                      ⇒ Seq(x)
    }
    ProcessRunner.runProcess(MashString(command) +: args, expandTilde = true)
    MashUnit
  }

  override def summary = s"Call the system command '$command'"

}